### ISSUE TITLE
how to run it in ros

### ISSUE THREAD

**Issue by zhang-mu-zhi** [Benjizhang/GCCD-PT#1]
I want to run the algorithm in ross but this algorithm is not packaged so I wonder how to proceed

I'm trying to make a package file myself and proceed, but I'm wondering if there's a better way.

**Comment by zhang-mu-zhi** [comment]
刚刚发现作者主在B站的视频。请问作者会考虑开源ROS部分的代码吗？或者将论文中Fig.7的代码开源？

**Comment by Benjizhang** [comment]
Hello, the code is still completed in Matlab, and there is no plan to convert it into a ros package. But welcome if you want to contribute to this repository : )
